Spp 9797 refactor example method files
ONSdigital/sml-python-small pull request #75
Opened 2024-01-26 10:27 UTC by jhmjam

## Synopsis

Briefly describe the purpose of the pr.

## Checklist

- [ ] Documentation created/updated
- [ ] Tests created/updated

## Description

Add a more detailed description of the pr including any necessary background
information.

2024-01-26 15:06 UTC, sanjeevz3009 requested changes

2024-01-29 12:18 UTC, jhmjam commented on sml_small/editing/totals_and_components/example.py
> +                            A,1625,632,732,99,162,TRUE,1625,,11,,,"""  # noqa: E501
All done :)

2024-01-30 12:09 UTC, sanjeevz3009 approved these changes
Looks good to me =) Pulled the branch down, tested it locally and all looks fine by me.

2024-01-30 12:09 UTC, sanjeevz3009 commented on sml_small/editing/totals_and_components/example.py
> +                            A,1625,632,732,99,162,TRUE,1625,,11,,,"""  # noqa: E501
Thank you ☺️

2024-01-30 12:11 UTC, merged